config/routes.rb
Kupon::Application.routes.draw do

  resources :regions

  resources :categories

  resources :akupons

  get "main/index"

  devise_for :users

  resources :promotions
  match 'promotions/:id/buyit' => 'promotions#buyit', :id => :id
  
  get "check/index"
  match '/check' => 'check#index'

  root :to => 'main#index'

end

app/models/akupon.rb
class Akupon < ActiveRecord::Base
  belongs_to :promotion
  belongs_to :user
end

app/controllers/akupons_controller.rb
class AkuponsController < ApplicationController
  require 'rqrcode'
  before_filter :authenticate_user!
  #check_authorization
  load_and_authorize_resource
  # GET /akupons
  # GET /akupons.json
  def index
    if current_user.role== 'admin'
      @akupons = Akupon.all
      render :template => 'akupons/index_admin'
    else   #for not admin
      @akupons = Akupon.where(:user_id => current_user.id)
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @akupons }
      end
    end
 

  end

  # GET /akupons/1
  # GET /akupons/1.json
  def show

    if current_user.role== 'admin'
      begin
        @akupon = Akupon.find(params[:id])
        render :template => 'akupons/show_admin'
      rescue
        redirect_to akupons_url
      end
    else   #for not admin
      begin
        @akupon = Akupon.where(:user_id => current_user.id, :id=>params[:id]).first
        
        @qr = RQRCode::QRCode.new(@akupon.unique_code)
        respond_to do |format|
          format.html # show.html.erb
          format.json { render json: @akupon }
        end
      rescue
        redirect_to akupons_url
      end
    end

    
    
    #    #@akupon = Akupon.find(2)
    #    @akupon = Akupon.where(:user_id => current_user.id, :id=>params[:id]).first
    #    #@akupon = Akupon.where(:id => current_user.id).first
    #
    #    respond_to do |format|
    #      format.html # show.html.erb
    #      format.json { render json: @akupon }
    #    end
  end

  # GET /akupons/new
  # GET /akupons/new.json
  def new
    @akupon = Akupon.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @akupon }
    end
  end

  # GET /akupons/1/edit
  def edit
    @akupon = Akupon.find(params[:id])
  end

  # POST /akupons
  # POST /akupons.json
  def create
    @akupon = Akupon.new(params[:akupon])

    respond_to do |format|
      if @akupon.save
        format.html { redirect_to @akupon, notice: 'Akupon was successfully created.' }
        format.json { render json: @akupon, status: :created, location: @akupon }
      else
        format.html { render action: "new" }
        format.json { render json: @akupon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /akupons/1
  # PUT /akupons/1.json
  def update
    @akupon = Akupon.find(params[:id])

    respond_to do |format|
      if @akupon.update_attributes(params[:akupon])
        format.html { redirect_to @akupon, notice: 'Akupon was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @akupon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /akupons/1
  # DELETE /akupons/1.json
  def destroy
    @akupon = Akupon.find(params[:id])
    @akupon.destroy

    respond_to do |format|
      format.html { redirect_to akupons_url }
      format.json { head :ok }
    end
  end
end

app/helpers/akupons_helper.rb
module AkuponsHelper
end

app/views/akupons/_form.html.erb
<%= form_for(@akupon) do |f| %>
  <% if @akupon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@akupon.errors.count, "error") %> prohibited this akupon from being saved:</h2>

      <ul>
      <% @akupon.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :promotion_id %><br />
    <%= f.number_field :promotion_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :purchase %><br />
    <%= f.date_select :purchase %>
  </div>
  <div class="field">
    <%= f.label :use %><br />
    <%= f.date_select :use %>
  </div>
  <div class="field">
    <%= f.label :unique_code %><br />
    <%= f.text_field :unique_code %>
  </div>
  <div class="field">
    <%= f.label :is_delete %><br />
    <%= f.check_box :is_delete %>
  </div>
  <div class="field">
    <%= f.label :is_canceled %><br />
    <%= f.check_box :is_canceled %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/akupons/edit.html.erb
<h1>Editing akupon</h1>

<%= render 'form' %>

<%= link_to 'Show', @akupon %> |
<%= link_to 'Back', akupons_path %>

app/views/akupons/index.html.erb
<h1>Купленные купоны</h1>

<table>
  <tr>
    <th>Акция</th>
    <th>Куплен</th>

    <th></th>
  </tr>

<% @akupons.each do |akupon| %>
  <tr>
    <td><%= akupon.promotion.title %></td>
    <td><%= akupon.purchase %></td>
    <td><%= link_to 'Подробнее', akupon %></td>
  </tr>
<% end %>
</table>

app/views/akupons/index_admin.html.erb
<h1>Listing akupons ADMIN MODE</h1>

<table>
  <tr>
    <th>Promotion</th>
    <th>User</th>
    <th>Purchase</th>
    <th>Use</th>
    <th>Unique code</th>
    <th>Is delete</th>
    <th>Is canceled</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @akupons.each do |akupon| %>
  <tr>
    <td><%= akupon.promotion.title %></td>
    <td><%= akupon.user.email %></td>
    <td><%= akupon.purchase %></td>
    <td><%= akupon.use %></td>
    <td><%= akupon.unique_code %></td>
    <td><%= akupon.is_delete %></td>
    <td><%= akupon.is_canceled %></td>
    <td><%= link_to 'Show', akupon %></td>
    <td><%= link_to 'Edit', edit_akupon_path(akupon) %></td>
    <td><%= link_to 'Destroy', akupon, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Akupon', new_akupon_path %>

app/views/akupons/new.html.erb
<h1>New akupon</h1>

<%= render 'form' %>

<%= link_to 'Back', akupons_path %>

app/views/akupons/show.html.erb
<style type="text/css">
  table {
    border-width: 0;
    border-style: none;
    border-color: #0000ff;
    border-collapse: collapse;
  }
  td {
    border-width: 0;
    border-style: none;
    border-color: #0000ff;
    border-collapse: collapse;
    padding: 0;
    margin: 0;
    width: 10px;
    height: 10px;
  }
  td.black { background-color: #000; }
  td.white { background-color: #fff; }
</style>

<%= link_to 'Назад', akupons_path %>
<p id="notice"><%= notice %></p>
Купон куплен
<p>
  <b>Promotion:</b>
  <%= @akupon.promotion.title %>
</p>

<p>
  <b>User:</b>
  <%= @akupon.user.email %>
</p>

<p>
  <b>Purchase:</b>
  <%= @akupon.purchase %>
</p>

<p>
  <b>Use:</b>
  <%= @akupon.use %>
</p>

<p>
  <b>Unique code:</b>
  <%= @akupon.unique_code %>
</p>
<div class="qr">
  <table>
    <% @qr.modules.each_index do |x| -%>
      <tr>
        <% @qr.modules.each_index do |y| -%>
          <% if @qr.dark?(x,y) -%>
            <td class="black"/>
          <% else -%>
            <td class="white"/>
          <% end -%>
        <% end -%>
      </tr>
    <% end -%>
  </table>

</div>

<p>
  <b>Is delete:</b>
  <%= @akupon.is_delete %>
</p>

<p>
  <b>Is canceled:</b>
  <%= @akupon.is_canceled %>
</p>
<%= link_to 'Назад', akupons_path %>

app/views/akupons/show_admin.html.erb
<h1>Admin Mode</h1>
<p id="notice"><%= notice %></p>
Купон куплен
<p>
  <b>Promotion:</b>
  <%= @akupon.promotion.title %>
</p>

<p>
  <b>User:</b>
  <%= @akupon.user.email %>
</p>

<p>
  <b>Purchase:</b>
  <%= @akupon.purchase %>
</p>

<p>
  <b>Use:</b>
  <%= @akupon.use %>
</p>

<p>
  <b>Unique code:</b>
  <%= @akupon.unique_code %>
</p>

<p>
  <b>Is delete:</b>
  <%= @akupon.is_delete %>
</p>

<p>
  <b>Is canceled:</b>
  <%= @akupon.is_canceled %>
</p>


<%= link_to 'Edit', edit_akupon_path(@akupon) %> |
<%= link_to 'Back', akupons_path %>