config/routes.rb
Kupon::Application.routes.draw do

  resources :regions

  resources :categories

  resources :akupons

  get "main/index"

  devise_for :users

  resources :promotions
  match 'promotions/:id/buyit' => 'promotions#buyit', :id => :id
  
  get "check/index"
  match '/check' => 'check#index'

  root :to => 'main#index'

end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
  belongs_to :region
  belongs_to :category
  has_many :kupon
end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
  # GET /promotions
  # GET /promotions.json
  load_and_authorize_resource

  #before_filter :authenticate_user!, :only=>[:show]
  before_filter :authenticate_user!, :except => [:index, :show]
  def index

    if current_or_guest_user.role== 'admin'
      @promotions = Promotion.all
      render :template => 'promotions/index_admin'
    else
      @promotions = Promotion.all

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @promotions }
      end
    end

  end

  # GET /promotions/1
  # GET /promotions/1.json
  def show
    @promotion = Promotion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @promotion }
    end
  end

  # GET /promotions/new
  # GET /promotions/new.json
  def new
    @promotion = Promotion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @promotion }
    end
  end

  # GET /promotions/1/edit
  def edit
    @promotion = Promotion.find(params[:id])
    #  @categories = Category.all
  end

  # POST /promotions
  # POST /promotions.json
  def create
    @promotion = Promotion.new(params[:promotion])

    respond_to do |format|
      if @promotion.save
        format.html { redirect_to @promotion, notice: 'Promotion was successfully created.' }
        format.json { render json: @promotion, status: :created, location: @promotion }
      else
        format.html { render action: "new" }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /promotions/1
  # PUT /promotions/1.json
  def update
    @promotion = Promotion.find(params[:id])

    respond_to do |format|
      if @promotion.update_attributes(params[:promotion])
        format.html { redirect_to @promotion, notice: 'Promotion was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promotions/1
  # DELETE /promotions/1.json
  def destroy
    @promotion = Promotion.find(params[:id])
    @promotion.destroy

    respond_to do |format|
      format.html { redirect_to promotions_url }
      format.json { head :ok }
    end
  end
  
  def buyit
    authorize! :buyit, Promotion
    @akupon = Akupon.new
    @akupon.promotion_id=params[:id]
    @akupon.user_id=current_user.id
    @akupon.purchase= Date.today
    
    array= [0,1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,0]
    rand_array= array.sort{ rand() - 0.5 }
    u_code= rand_array[ 0..9 ]
    @akupon.unique_code= u_code.join(sep=$,) 
    #@akupon.unique_code="safdfjioewroiwyr"
    
    
    
    @akupon.is_canceled= false
    @akupon.is_delete= false
    @akupon.save
    #  redirect_to promotion_path(@post)
    redirect_to akupon_path(@akupon)
  end
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/views/promotions/_form.html.erb
<%= form_for(@promotion) do |f| %>
  <% if @promotion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@promotion.errors.count, "error") %> prohibited this promotion from being saved:</h2>

      <ul>
      <% @promotion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :region_id %><br />
    <%#= f.number_field :region_id %>
    <%= f.select(:region_id, Region.all.collect {|p| [ p.name_region, p.id ] })%>
  </div>
  <div class="field">
    <%= f.label :partner_id %><br />
    <%= f.number_field :partner_id %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%#= f.number_field :category_id %>


    <%#= select_tag (:category_id, :id, @categories.map {|u| [u.name,u.id]}) %>
    <%#= options_from_collection_for_select(Category.all, :id, :name) %>
    <%#= select(:category_id, :category_id, Category.all.collect {|p| [ p.name, p.id ] })%>
     <%#= f.select(:category_id,[['Lisbon', 1], ['Madrid', 2]]) %>
    <%= f.select(:category_id, Category.all.collect {|p| [ p.name, p.id ] })%>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :is_active %><br />
    <%= f.check_box :is_active %>
  </div>
  <div class="field">
    <%= f.label :is_delete %><br />
    <%= f.check_box :is_delete %>
  </div>
  <div class="field">
    <%= f.label :who_delete %><br />
    <%= f.text_field :who_delete %>
  </div>
  <div class="field">
    <%= f.label :on_top %><br />
    <%= f.check_box :on_top %>
  </div>
  <div class="field">
    <%= f.label :start_action %><br />
    <%= f.date_select :start_action %>
  </div>
  <div class="field">
    <%= f.label :stop_action %><br />
    <%= f.date_select :stop_action %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :short_description %><br />
    <%= f.text_area :short_description %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :terms %><br />
    <%= f.text_area :terms %>
  </div>
  <div class="field">
    <%= f.label :costs %><br />
    <%= f.text_field :costs %>
  </div>
  <div class="field">
    <%= f.label :volume %><br />
    <%= f.number_field :volume %>
  </div>
  <div class="field">
    <%= f.label :left %><br />
    <%= f.number_field :left %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/promotions/edit.html.erb
<h1>Editing promotion</h1>

<%= render 'form' %>

<%= link_to 'Show', @promotion %> |
<%= link_to 'Back', promotions_path %>

app/views/promotions/index.html.erb
<h1>Акции</h1>
<table>
  <tr>
    <th>Категория</th>
    <th>Начало акции</th>
    <th>окончание акции</th>
    <th>название</th>
    <th>Стоимость</th>
    <th>Осталось</th>
    <th></th>
  </tr>

<% @promotions.each do |promotion| %>
  <tr>
    <td><%= promotion.category.name %></td>
    <td><%= promotion.start_action %></td>
    <td><%= promotion.stop_action %></td>
    <td><%= promotion.title %></td>
    <td><%= promotion.costs %></td>
    <td><%= promotion.left %></td>
    <td><%= link_to 'Подробнее', promotion %></td>
  </tr>
<% end %>
</table>

<br />

app/views/promotions/index_admin.html.erb
<h1>Listing promotions ADMIN MODE</h1>
<%= link_to 'New Promotion', new_promotion_path %>
<table>
  <tr>
    <th>Region</th>
    <th>Partner</th>
    <th>Category</th>
    <th>User</th>
    <th>Is active</th>
    <th>Is delete</th>
    <th>Who delete</th>
    <th>On top</th>
    <th>Start action</th>
    <th>Stop action</th>
    <th>Title</th>

    <th>Costs</th>
    <th>Volume</th>
    <th>Left</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @promotions.each do |promotion| %>
  <tr>
    <td><%= promotion.region.name_region %></td>
    <td><%= promotion.partner_id %></td>
    <td><%= promotion.category.name %></td>
    <td><%= promotion.user_id %></td>
    <td><%= promotion.is_active %></td>
    <td><%= promotion.is_delete %></td>
    <td><%= promotion.who_delete %></td>
    <td><%= promotion.on_top %></td>
    <td><%= promotion.start_action %></td>
    <td><%= promotion.stop_action %></td>
    <td><%= promotion.title %></td>

    <td><%= promotion.costs %></td>
    <td><%= promotion.volume %></td>
    <td><%= promotion.left %></td>
    <td><%= link_to 'Show', promotion %></td>
    <td><%= link_to 'Edit', edit_promotion_path(promotion) %></td>
    <td><%= link_to 'Destroy', promotion, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Promotion', new_promotion_path %>

app/views/promotions/new.html.erb
<h1>New promotion</h1>

<%= render 'form' %>

<%= link_to 'Back', promotions_path %>

app/views/promotions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Region:</b>
  <%= @promotion.region.name_region %>
</p>

<p>
  <b>Partner:</b>
  <%= @promotion.partner_id %>
</p>

<p>
  <b>Category:</b>
  <%= @promotion.category.name %>
</p>

<p>
  <b>User:</b>
  <%= @promotion.user_id %>
</p>

<p>
  <b>Is active:</b>
  <%= @promotion.is_active %>
</p>

<p>
  <b>Is delete:</b>
  <%= @promotion.is_delete %>
</p>

<p>
  <b>Who delete:</b>
  <%= @promotion.who_delete %>
</p>

<p>
  <b>On top:</b>
  <%= @promotion.on_top %>
</p>

<p>
  <b>Start action:</b>
  <%= @promotion.start_action %>
</p>

<p>
  <b>Stop action:</b>
  <%= @promotion.stop_action %>
</p>

<p>
  <b>Title:</b>
  <%= @promotion.title %>
</p>

<p>
  <b>Short description:</b>
  <%= @promotion.short_description %>
</p>

<p>
  <b>Description:</b>
  <%= @promotion.description %>
</p>

<p>
  <b>Terms:</b>
  <%= @promotion.terms %>
</p>

<p>
  <b>Costs:</b>
  <%= @promotion.costs %>
</p>

<p>
  <b>Volume:</b>
  <%= @promotion.volume %>
</p>

<p>
  <b>Left:</b>
  <%= @promotion.left %>
</p>
<%#*<h2><%= link_to 'Edit', buyit_promotion_path(@promotion) %> |</h2>%>

<h2><%= link_to "Купить", :controller => "promotions", :action => "buyit", :id => @promotion  %></h2>

<%= link_to 'Edit', edit_promotion_path(@promotion) %> |
<%= link_to 'Back', promotions_path %>