config/routes.rb
Kupon::Application.routes.draw do

  resources :regions

  resources :categories

  resources :akupons

  get "main/index"

  devise_for :users

  resources :promotions
  match 'promotions/:id/buyit' => 'promotions#buyit', :id => :id
  
  get "check/index"
  match '/check' => 'check#index'

  root :to => 'main#index'

end

app/models/region.rb
class Region < ActiveRecord::Base
  has_many :promotion
  has_many :user
  has_many :category
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  # GET /regions
  # GET /regions.json
  load_and_authorize_resource
  def index
    @regions = Region.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @regions }
    end
  end

  # GET /regions/1
  # GET /regions/1.json
  def show
    @region = Region.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @region }
    end
  end

  # GET /regions/new
  # GET /regions/new.json
  def new
    @region = Region.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @region }
    end
  end

  # GET /regions/1/edit
  def edit
    @region = Region.find(params[:id])
  end

  # POST /regions
  # POST /regions.json
  def create
    @region = Region.new(params[:region])

    respond_to do |format|
      if @region.save
        format.html { redirect_to @region, notice: 'Region was successfully created.' }
        format.json { render json: @region, status: :created, location: @region }
      else
        format.html { render action: "new" }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /regions/1
  # PUT /regions/1.json
  def update
    @region = Region.find(params[:id])

    respond_to do |format|
      if @region.update_attributes(params[:region])
        format.html { redirect_to @region, notice: 'Region was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regions/1
  # DELETE /regions/1.json
  def destroy
    @region = Region.find(params[:id])
    @region.destroy

    respond_to do |format|
      format.html { redirect_to regions_url }
      format.json { head :ok }
    end
  end
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/regions/_form.html.erb
<%= form_for(@region) do |f| %>
  <% if @region.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@region.errors.count, "error") %> prohibited this region from being saved:</h2>

      <ul>
      <% @region.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name_region %><br />
    <%= f.text_field :name_region %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :is_active %><br />
    <%= f.check_box :is_active %>
  </div>
  <div class="field">
    <%= f.label :is_delete %><br />
    <%= f.check_box :is_delete %>
  </div>
  <div class="field">
    <%= f.label :who_delete %><br />
    <%= f.text_field :who_delete %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/regions/edit.html.erb
<h1>Editing region</h1>

<%= render 'form' %>

<%= link_to 'Show', @region %> |
<%= link_to 'Back', regions_path %>

app/views/regions/index.html.erb
<h1>Listing regions</h1>

<table>
  <tr>
    <th>Name region</th>
    <th>Description</th>
    <th>Is active</th>
    <th>Is delete</th>
    <th>Who delete</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @regions.each do |region| %>
  <tr>
    <td><%= region.name_region %></td>
    <td><%= region.description %></td>
    <td><%= region.is_active %></td>
    <td><%= region.is_delete %></td>
    <td><%= region.who_delete %></td>
    <td><%= link_to 'Show', region %></td>
    <td><%= link_to 'Edit', edit_region_path(region) %></td>
    <td><%= link_to 'Destroy', region, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Region', new_region_path %>

app/views/regions/new.html.erb
<h1>New region</h1>

<%= render 'form' %>

<%= link_to 'Back', regions_path %>

app/views/regions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name region:</b>
  <%= @region.name_region %>
</p>

<p>
  <b>Description:</b>
  <%= @region.description %>
</p>

<p>
  <b>Is active:</b>
  <%= @region.is_active %>
</p>

<p>
  <b>Is delete:</b>
  <%= @region.is_delete %>
</p>

<p>
  <b>Who delete:</b>
  <%= @region.who_delete %>
</p>


<%= link_to 'Edit', edit_region_path(@region) %> |
<%= link_to 'Back', regions_path %>